export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_DRAWER_MENU = 'TOGGLE_DRAWER_MENU';
export const SET_MENU_ACTIVE = 'SET_MENU_ACTIVE';
export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCESSFUL = 'FETCH_MENU_SUCCESSFUL';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';

