export const LOAD_FORM = 'LOAD_FORM';
export const LOAD_FORM_SUCCESSFUL = 'LOAD_FORM_SUCCESSFUL';
export const LOAD_FORM_FAILURE = 'LOAD_FORM_FAILURE';
export const SAVE_FORM = 'SAVE_FORM';
export const SAVE_FORM_SUCCESSFUL = 'SAVE_FORM_SUCCESSFUL';
export const SAVE_FORM_FAILURE = 'SAVE_FORM_FAILURE';
