export const LOAD_FORM = 'LOAD_FORM';
export const LOAD_FORM_SUCCESSFUL = 'LOAD_FORM_SUCCESSFUL';
export const LOAD_FORM_FAILURE = 'LOAD_FORM_FAILURE';
export const SET_FORM_SAVING = 'SET_FORM_SAVING';
export const SET_FORM_VALIDATION_FAILURE = 'SET_FORM_VALIDATION_FAILURE';
