export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_DRAWER_MENU = 'TOGGLE_DRAWER_MENU';
export const SET_APP_LOADING = 'SET_APP_LOADING';
export const SET_MENU_TITLE = 'SET_MENU_TITLE';
export const SET_MENU_ACTIVE = 'SET_MENU_ACTIVE';

