export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_SUCCESSFUL = 'AUTHENTICATE_USER_SUCCESSFUL';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESSFUL = 'FETCH_USER_SUCCESSFUL';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
