export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_SUCCESSFUL = 'AUTHENTICATE_USER_SUCCESSFUL';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';
export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
export const SET_USER_AUTHORIZATION = 'SET_USER_AUTHORIZATION';
export const RESET_USER_AUTHORIZATION = 'RESET_USER_AUTHORIZATION';
